{
   "swagger":"2.0",
   "info":{
      "version":"1.0.0",
      "title":"UniCity API",
      "description":"The specification for the UniCity API. This API provides data on the cities in which universities are located."
   },
   "basePath":"/api",
   "tags":[
      {
         "name":"Cities",
         "description":"The route for retrieving the available cities and their descriptions"
      },
      {
         "name":"All Data",
         "description":"The routes for retrieving all the available data for cities"
      },
      {
         "name":"Rent",
         "description":"The routes for retrieving the rent data for cities"
      },
      {
         "name":"Broadband Speed",
         "description":"The routes for retrieving the average download speed (Mbps) for cities"
      },
      {
         "name":"Crime",
         "description":"The routes for retrieving the crime data (per 1000 people) for cities"
      },
      {
         "name":"Wages",
         "description":"The routes for retrieving the wage data for cities"
      },
      {
         "name":"Food",
         "description":"The routes for retrieving the food data for cities"
      },
   ],
   "schemes":[
      "http"
   ],
   "consumes":[
      "application/json"
   ],
   "produces":[
      "application/json"
   ],
   "paths":{
      "/cities":{
         "get":{
            "tags":[
               "Cities"
            ],
            "description":"Returns the available cities",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "responses":{
               "200":{
                  "description":"The success response for the cities request",
                  "schema":{
                     "$ref":"#/definitions/cities-success-response"
                  }
               }
            }
         }
      },
      "/all-data/{city}":{
         "get":{
            "tags":[
               "All Data"
            ],
            "description":"Returns all the available data for the city",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "name":"city",
                  "in":"path",
                  "description":"City to fetch all data for",
                  "required":true,
                  "type":"string"
               }
            ],
            "responses":{
               "200":{
                  "description":"The success response for an all data request",
                  "schema":{
                     "$ref":"#/definitions/all-data-success-response"
                  }
               },
               "404":{
                  "description":"The failure response for an all data request",
                  "schema":{
                     "$ref":"#/definitions/failure-response"
                  }
               }
            }
         }
      },
      "/all-data/all-cities":{
         "get":{
            "tags":[
               "All Data"
            ],
            "description":"Returns all the available data for all the available cities",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "responses":{
               "200":{
                  "description":"The success response for an all data request",
                  "schema":{
                     "$ref":"#/definitions/all-data-all-cities-success-response"
                  }
               }
            }
         }
      },
      "/rent/{city}":{
         "get":{
            "tags":[
               "Rent"
            ],
            "description":"Returns the monthly rent data for a single room in the city",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "name":"city",
                  "in":"path",
                  "description":"City to fetch the rent data for",
                  "required":true,
                  "type":"string"
               }
            ],
            "responses":{
               "200":{
                  "description":"The success response for a rent request",
                  "schema":{
                     "$ref":"#/definitions/rent-success-response"
                  }
               },
               "404":{
                  "description":"The failure response for a rent request",
                  "schema":{
                     "$ref":"#/definitions/failure-response"
                  }
               }
            }
         }
      },
      "/rent/all-cities":{
         "get":{
            "tags":[
               "Rent"
            ],
            "description":"Returns the monthly rent data for a single room in the all the cities available",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "responses":{
               "200":{
                  "description":"The success response for a rent request for all available cities",
                  "schema":{
                     "$ref":"#/definitions/rent-all-cities-success-response"
                  }
               }
            }
         }
      },
      "/nightlife/{city}":{
         "get":{
            "tags":[
               "Nightlife Rating"
            ],
            "description":"Returns the nightlife rating for the city",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "name":"city",
                  "in":"path",
                  "description":"City to fetch the nightlife rating for",
                  "required":true,
                  "type":"string"
               }
            ],
            "responses":{
               "200":{
                  "description":"The success response for a nightlife rating request",
                  "schema":{
                     "$ref":"#/definitions/nightlife-success-response"
                  }
               },
               "404":{
                  "description":"The failure response for a nightlife rating request",
                  "schema":{
                     "$ref":"#/definitions/failure-response"
                  }
               }
            }
         }
      },
      "/nightlife/all-cities":{
         "get":{
            "tags":[
               "Nightlife Rating"
            ],
            "description":"Returns the nightlife ratings for all available cities",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "responses":{
               "200":{
                  "description":"The success response for a nightlife rating request for all available cities",
                  "schema":{
                     "$ref":"#/definitions/nightlife-all-cities-success-response"
                  }
               }
            }
         }
      },
      "/broadband/{city}":{
         "get":{
            "tags":[
               "Broadband Speed"
            ],
            "description":"Returns the average download speed (Mbps) for the city",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "name":"city",
                  "in":"path",
                  "description":"City to fetch the average download speed for",
                  "required":true,
                  "type":"string"
               }
            ],
            "responses":{
               "200":{
                  "description":"The success response for a broadband speed request",
                  "schema":{
                     "$ref":"#/definitions/broadband-success-response"
                  }
               },
               "404":{
                  "description":"The failure response for a broadband request",
                  "schema":{
                     "$ref":"#/definitions/failure-response"
                  }
               }
            }
         }
      },
      "/broadband/all-cities":{
         "get":{
            "tags":[
               "Broadband Speed"
            ],
            "description":"Returns the average download speed (Mbps) for all the available cities",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "responses":{
               "200":{
                  "description":"The success response for a broadband speed request for all available cities",
                  "schema":{
                     "$ref":"#/definitions/broadband-all-cities-success-response"
                  }
               }
            }
         }
      },
      "/crime/{city}":{
         "get":{
            "tags":[
               "Crime"
            ],
            "description":"Returns the crime data (per 1000 people) for the city",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "name":"city",
                  "in":"path",
                  "description":"City to fetch the crime data for",
                  "required":true,
                  "type":"string"
               }
            ],
            "responses":{
               "200":{
                  "description":"The success response for a crime data request",
                  "schema":{
                     "$ref":"#/definitions/crime-success-response"
                  }
               },
               "404":{
                  "description":"The failure response for a crime data request",
                  "schema":{
                     "$ref":"#/definitions/failure-response"
                  }
               }
            }
         }
      },
      "/crime/all-cities":{
         "get":{
            "tags":[
               "Crime"
            ],
            "description":"Returns the crime data (per 1000 people) for all the available cities",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "responses":{
               "200":{
                  "description":"The success response for a crime data request for all available cities",
                  "schema":{
                     "$ref":"#/definitions/crime-all-cities-success-response"
                  }
               }
            }
         }
      },
    "/wages/{city}":{
         "get":{
            "tags":[
               "Wages"
            ],
            "description":"Returns the average annual salary in the city",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "name":"city",
                  "in":"path",
                  "description":"City to fetch the wage data for",
                  "required":true,
                  "type":"string"
               }
            ],
            "responses":{
               "200":{
                  "description":"The success response for a wages request",
                  "schema":{
                     "$ref":"#/definitions/wages-success-response"
                  }
               },
               "404":{
                  "description":"The failure response for a wages request",
                  "schema":{
                     "$ref":"#/definitions/failure-response"
                  }
               }
            }
         }
      },
      "/wages/all-cities":{
         "get":{
            "tags":[
               "Wages"
            ],
            "description":"Returns the average annual salary for all the cities available",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "responses":{
               "200":{
                  "description":"The success response for a wages request for all available cities",
                  "schema":{
                     "$ref":"#/definitions/wages-all-cities-success-response"
                  }
               }
            }
         }
      },
      "/food/{city}":{
         "get":{
            "tags":[
               "Food"
            ],
            "description":"Returns the average weekly food expenditure in the city",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "name":"city",
                  "in":"path",
                  "description":"City to fetch the food data for",
                  "required":true,
                  "type":"string"
               }
            ],
            "responses":{
               "200":{
                  "description":"The success response for a food request",
                  "schema":{
                     "$ref":"#/definitions/food-success-response"
                  }
               },
               "404":{
                  "description":"The failure response for a food request",
                  "schema":{
                     "$ref":"#/definitions/failure-response"
                  }
               }
            }
         }
      },
      "/food/all-cities":{
         "get":{
            "tags":[
               "Food"
            ],
            "description":"Returns the average weekly food costs for all the cities available",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "responses":{
               "200":{
                  "description":"The success response for a food request for all available cities",
                  "schema":{
                     "$ref":"#/definitions/food-all-cities-success-response"
                  }
               }
            }
         }
      },
      "/food/all-regions":{
         "get":{
            "tags":[
               "Food"
            ],
            "description":"Returns the average weekly food costs for all the regions available",
            "operationId":"",
            "produces":[
               "application/json"
            ],
            "responses":{
               "200":{
                  "description":"The success response for a food request for all available regions",
                  "schema":{
                     "$ref":"#/definitions/food-all-regions-success-response"
                  }
               }
            }
         }
      },
    },
  "definitions":{
      "cities-success-response":{
         "type":"array",
         "items":{
            "properties":{
               "name":{
                  "required":true,
                  "type":"string",
                  "example":"Southampton"
               },
               "region": {
                  "required":true,
                  "type":"string",
                  "example":"South East" 
               },
               "description":{
                  "required":true,
                  "type":"schema",
                  "example":""
               }
            }
         }
      },
      "all-data-success-response":{
         "properties":{
            "city":{
               "required":true,
               "type":"string",
               "example":"Southampton"
            },
            "rent":{
               "required":true,
               "type":"schema",
               "example":{
                  "median":"355",
                  "mean":"368",
                  "rating":"Above Average"
               }
            },
            "nightlife":{
               "required":true,
               "type":"schema",
               "example":{
                  "rating":"3.7"
               }
            },
            "broadband":{
               "required":true,
               "type":"schema",
               "example":{
                  "speed":"27.03",
                  "rating":"Above Average"
               }
            }
         }
      },
      "all-data-all-cities-success-response":{
         "type":"array",
         "items":{
            "properties":{
               "city":{
                  "required":true,
                  "type":"string",
                  "example":"Southampton"
               },
               "rent":{
                  "required":true,
                  "type":"schema",
                  "example":{
                     "median":"355",
                     "mean":"368",
                     "rating":"Above Average"
                  }
               },
               "nightlife":{
                  "required":true,
                  "type":"schema",
                  "example":{
                     "rating":"3.7"
                  }
               },
               "broadband":{
                  "required":true,
                  "type":"schema",
                  "example":{
                     "speed":"27.03",
                     "rating":"Above Average"
                  }
               }
            }
         }
      },
      "rent-success-response":{
         "properties":{
            "city":{
               "required":true,
               "type":"string",
               "example":"Southampton"
            },
            "rent":{
               "required":true,
               "type":"schema",
               "example":{
                  "median":"355",
                  "mean":"368",
                  "rating":"Above Average"
               }
            }
         }
      },
      "failure-response":{
         "properties":{
            "status":{
               "required":true,
               "type":"number",
               "example":"404"
            },
            "message":{
               "required":true,
               "type":"schema",
               "example":"Invalid city"
            }
         }
      },
      "rent-all-cities-success-response":{
         "type":"array",
         "items":{
            "properties":{
               "city":{
                  "required":true,
                  "type":"string",
                  "example":"Southampton"
               },
               "rent":{
                  "required":true,
                  "type":"schema",
                  "example":{
                     "median":"355",
                     "mean":"368",
                     "rating":"Above Average"
                  }
               }
            }
         }
      },
      "nightlife-success-response":{
         "properties":{
            "city":{
               "required":true,
               "type":"string",
               "example":"Southampton"
            },
            "nightlife":{
               "required":true,
               "type":"schema",
               "example":{
                  "rating":"3.7"
               }
            }
         }
      },
      "nightlife-all-cities-success-response":{
         "type":"array",
         "items":{
            "properties":{
               "city":{
                  "required":true,
                  "type":"string",
                  "example":"Southampton"
               },
               "nightlife":{
                  "required":true,
                  "type":"schema",
                  "example":{
                     "rating":"3.7"
                  }
               }
            }
         }
      },
      "broadband-success-response":{
         "properties":{
            "city":{
               "required":true,
               "type":"string",
               "example":"Southampton"
            },
            "broadband":{
               "required":true,
               "type":"schema",
               "example":{
                  "speed":"27.03",
                  "rating":"Above Average"
               }
            }
         }
      },
      "broadband-all-cities-success-response":{
         "type":"array",
         "items":{
            "properties":{
               "city":{
                  "required":true,
                  "type":"string",
                  "example":"Southampton"
               },
               "broadband":{
                  "required":true,
                  "type":"schema",
                  "example":{
                     "speed":"27.03",
                     "rating":"Above Average"
                  }
               }
            }
         }
      },
      "crime-success-response":{
         "properties":{
            "city":{
               "required":true,
               "type":"string",
               "example":"Southampton"
            },
            "crimeData":{
               "required":true,
               "type":"schema",
               "example":{
                  "robbery":"10",
                  "burglary":"368",
                  "violenceAndSexualOffences":"19.2",
                  "total":"30.1",
                  "rating":"Below Average"
               }
            }
         }
      },
      "crime-all-cities-success-response":{
         "type":"array",
         "items":{
            "properties":{
               "city":{
                  "required":true,
                  "type":"string",
                  "example":"Southampton"
               },
               "crimeData":{
                  "required":true,
                  "type":"schema",
                  "example":{
                     "robbery":"10",
                     "burglary":"368",
                     "violenceAndSexualOffences":"19.2",
                     "total":"30.1",
                     "rating":"Below Average"
                  }
               }
            }
         }
      },
      "wages-success-response":{
         "properties":{
            "city":{
               "required":true,
               "type":"string",
               "example":"Southampton"
            },
            "wages":{
               "required":true,
               "type":"schema",
               "example":{
                  "average":"21035.67",
                  "rating":"Below Average"
               }
            }
         }
      },
      "wages-all-cities-success-response":{
         "type":"array",
         "items":{
            "properties":{
               "city":{
                  "required":true,
                  "type":"string",
                  "example":"Southampton"
               },
               "wages":{
                  "required":true,
                  "type":"schema",
                  "example":{
                    "average":"21035.67",
                    "rating":"Below Average"
                  }
               }
            }
         }
      },
       "food-success-response":{
         "properties":{
            "city":{
               "required":true,
               "type":"string",
               "example":"Southampton"
            },
            "food":{
               "required":true,
               "type":"schema",
               "example":{
                  "region":"South East",
                  "foodAverage":"26.75",
                  "foodRating":"Above average",
                  "narcoticAverage":"5.21",
                  "narcoticRating":"Above Average"
               }
            }
         }
      },
      "food-all-cities-success-response":{
         "type":"array",
         "items":{
            "properties":{
               "city":{
                  "required":true,
                  "type":"string",
                  "example":"Southampton"
               },
               "wages":{
                  "required":true,
                  "type":"schema",
                  "example":{
                     "region":"South East",
                     "foodAverage":"26.75",
                     "foodRating":"Above average",
                     "narcoticAverage":"5.21",
                     "narcoticRating":"Above Average"
                  }
               }
            }
         }
      },
      "food-all-regions-success-response":{
         "type":"array",
         "items":{
            "properties":{
               "region":{
                  "required":true,
                  "type":"string",
                  "example":"South East"
               },
               "foodAverage": {
                  "required":true,
                  "type":"string",
                  "example":"26.75" 
               },
               "foodRating":{
                  "required":true,
                  "type":"string",
                  "example":"Above average"
               },
               "narcoticAverage": {
                  "required":true,
                  "type":"string",
                  "example":"5.21" 
               },
               "narcoticRating":{
                  "required":true,
                  "type":"string",
                  "example":"Above average"
               }
            }
         }
      },
   }
}
